#!/usr/bin/env bash
npm install

# força plugins a serem baixados
ionic platform add android

# correção
cp NetworkingBluetooth.java plugins/cordova-plugin-networking-bluetooth/src/android

# força o plugin a ser recopiado
ionic platform remove android
ionic platform add android

ionic run android
